import type { NextPage } from 'next'
import styled from 'styled-components'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import {TailwindButton} from './StyledButton.style'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <StyledButton>Button</StyledButton>
    <br/>
    <TailwindButton>Tailwind</TailwindButton>

    </div>
  )
}

export default Home



const StyledButton = styled.button`
  background: red;
  color: white;
  font-size: 1em;
  padding: .25em 1em;
  border: 2px solid black;
`